name: Package Application with Pyinstaller

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src

    - uses: canastro/copy-file-action@master
      with:
        source: "src/bat-files/start.bat"
        target: "dist/start.bat"

    - uses: canastro/copy-file-action@master
      with:
        source: "src/bat-files/learn.bat"
        target: "dist/learn.bat"

    - uses: actions/upload-artifact@v2
      with:
        name: midiosc
        path: dist